[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
AMQP_URL = "amqp://guest:guest@amqp-broker.railway.internal:5672"
AMQP_EXCHANGE = "citrineos"
QUEUE_NAME = "extensions-service"
CITRINEOS_API_URL = "http://citrineos-core.railway.internal:8080"
PORT = "3001"
