FROM ghcr.io/citrineos/citrineos-directus:latest

EXPOSE 8055

ENV KEY=change-me-to-a-random-key
ENV SECRET=change-me-to-a-random-secret
ENV ADMIN_EMAIL=admin@citrineos.com
ENV ADMIN_PASSWORD=CitrineOS!
ENV EXTENSIONS_AUTO_RELOAD=true
ENV EXTENSIONS_CACHE_TTL=1s
ENV DB_CLIENT=pg
ENV WEBSOCKETS_ENABLED=true
